# Generated by Django 3.0.7 on 2020-08-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('ERROR', 'error'), ('DEBUG', 'debug'), ('WARNING', 'warning')], max_length=30)),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Produção'), ('HOMOLOGATION', 'Homologação'), ('DEVELOPMENT', 'Desenvolvimento')], max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.Agent')),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.AppException')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
